### ISSUE TITLE
[BUG] Firefox Compatibility - Web RTC Connection Negotiated

### ISSUE THREAD

**Issue by marospekarik** [DimensionLab/pixel-streaming-infrastructure#6]
<img width="904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXVMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d81cb51736963c5bc1a7d604a32ac26724c5e6a/image.png" alt="image.png" />

Suddenly, I cannot access any stream on Firefox. Maybe related to this issue: https://github.com/EpicGames/PixelStreamingInfrastructure/issues/460

**Comment by marospekarik** [comment]
Adding Safari to the scope as well

**Comment by marospekarik** [comment]
@martin-muzelak 
![image](https://github.com/DimensionLab/pixel-streaming-infrastructure/assets/14806065/9b5c6db6-47e5-440a-b923-1ed28a2100ea)

**Comment by martin-muzelak** [comment]
So we need to update rules in security group for SITEs.
